FROM relateiq/oracle-java8
VOLUME /tmp
RUN mkdir -p /opt/api/
COPY target/*.jar /opt/api/app.jar
#ENTRYPOINT ["java","-Dspring.profiles.active=dev","-Dserver.port=8080","-Dspring.datasource.url=jdbc:sybase:Tds:${DATABASE_AC_HOST}:${DATABASE_AC_PORT}/APLICATION","-Dspring.datasource.username=${DATABASE_AC_USER}","-Dspring.datasource.password=${DATABASE_AC_PASSWORD}","-jar","/opt/api/app.jar"]
ENTRYPOINT ["java","-Dspring.profiles.active=dev","-Dserver.port=8080","-jar","/opt/api/app.jar"]